language: java
jdk:
  - oraclejdk8

notifications:
  email: false

cache:
  directories:
  - "$HOME/.m2"

before_install: 
  - sed -i -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - unzip ./src/main/resources/repogit4testv0.zip

after_success:
  - .buildscript/deploy_to_maven.sh

dist: trusty
