env:
  global:
     ## CI_DEPLOY_USERNAME
     - secure: qLgIK7ijG9C6Hpu2iSVp+VkJ3mw23lSo66MP85Q85gNqS68CDuNYr4xeI0Nute7NfXf6I8Hij8UgGUCcGOyDFN548tlmSMypSGENgtXsMYHLFFOtQipO1cMPUel/HiN2hvnxyYiaVIbTTO7PfR1PGicqoEiidmc7VDGZCqIxNANJ68bn+/5GuQXt/OTGom4T8lS2txO8EyUH34MiUa0Xsl/ZG5vjZBxzvyIbRlCfljCL16k1WLxj/Uri9izeeJ+ND9SdvKOEGrKnMeKYsnGs6NlAWVuZ0GXYKsYC81MsxPIwz88HUu0iUA7bfZWzgCFbWGSCvKJLTekJOf+TgOvqaBBR6rjTDJwqXXXd3kOtHNxJOQEXgzwWle3399OlRUcICpOE5z3Ths4byTbWVEKueP4sfMs9Ekwi9hDGGyjPr83x2Pw/ZbjU82oI89o985KOpd2lhirSEs/LmufBJgcr/B005Aj9x4t3j0CqlvnOo4WNheUGcwTRa2Z2wHJJ7m7ZmSgglyJn6m8D2fzLsIXCjiF3i7WdGDR+GUj/bEDXkzHwFgZ9T9J4+eAh+DpYlQRUojcghrw8SaTOECRgSYIfL+/gqkWkwX7XdWQCafFmCbRP4RtaLyWkyWyVLBsHOLObqeV6KBWxX9r9iVPdUnmReIvJfgkLZ7ZG43dkBYte3f8=
     ## CI_DEPLOY_PASSWOR
     - secure: oWZ/45eADCgpHAJ0VZsR+cr+QXKx/avmGpbTOYypbYrKm1wuPKsOM0bJt2GJSGI5wU3Ks0BxPGe9V4y64cfVHp4MCUal1JHLlbVGPBP5dbX1FXr81WUn6VmsgdeX5fYvkXvWSzoQnEMQaUhxhaQ3nRUu8MHKXShwlMhy6kUBji1WyDCJJhLnNs2fJNBUyYm7pbrnYx74R4sURvQ3ffMeHbvU4gAOCbFre1Aq7XeaQaGL+coJE26AmsXG0tlnIJ7JnzDxArkonDt+xHpMIY5SweslTKUhahcrazgFGaGCjObmvkVRvCizJGsLgm40w0PXa1uX6jauYGD3S0WR0RL8fr8GYfRdkmEWIT85OPgDShPB/0WA22cg26Tv+IvtRBqxRYOK3Tnx3Grf79/s7o5hyVlol6rDDKH9rkzGQaw3IDZorsnwjdb4G1wLDWNQu2B5PeJahNtAh4737G8atAHWrMvmXzOhEqJ9LuzBDshBm5BybqnJ+jf6C8VBlTb2+TLBjfwIrYplURVqnfbJ2AsFtk9FYIRwMm6B8GBaEL9reckV8Rn7cHSlZSpPT+mhnkxb1EdCi8dh5PTpoWw1uzuQRaDxzu/O4tATosGpiIDxTJ2Chm7XjKrnmT7580rZHOcsweRozZsNej1yVAJKfG8e/fom26gz/F5wwPoBRTYywmQ=
     ## GPG_KEY_NAME
     - secure: k5J/cRKkWoI4jABZNzEVy4xqnLiUsw/Zc0d3AbYucpzzkBEW+Vrmr7GtcEgRZ3+OhaL7V+f66MaNDOclnTV5AJI6do+HEC9XbCySmqCBueOwMKJQFIQEHOvgjGB/9YLDjzLR13Idhiowl8zgQiMwWi7hYuwegafWyLvoD8IK5mCkovGw/j01R6XvofYD/o+Yeqtfe6flXEa9B3+0Q8fQ5/wsRowJUIHNgvCDFREyehKLQNTexU1TPC3tz1mpFDjjlm5bRAL3BJzK7fgyoNvQDss+1MCD0RO6may0CfZd5ZOIVsc38bjU/NaowpJCr80P2wQw05Aje9GKaXad/SrOj13FzthVbCvX9jHffSOuA2tMfwP3UcHZ2EHfrQEB0bzttmmLQA07N4XJ1MQHMEz4wVgz9vC9g+LWrWKM0Q7AThxj6+V49ulnNR/wJbH8E0MCStibarq3mbGxjWW/zyM4ArwPUrILc3kznlbzkKHyNY22bskqRiDu9Yy/c7HVSITWrt3EdYd+dz8hxJ/YxR8d9Irm4LVWoMSd4SKWXYAqRpu0T8DgIcv/2qHT6X78jrO6DV/WfAhzKctX4t3GSB6LNL3hlB74NBadCUh4Uf/wJiicEQYyWDBt5lf3kisSyR4LpQhSryddvbrOIMqqeIPnmdcTdBVGHDuW4o6pcC36rFU=
     ## GPG_PASSPHRASE
     - secure: NdS+m9y572BV7ftCZxygNMDWBihIXn1AkbiWFnBAV42u4lsh0V2q99p/cw4plQMhAXbi5Qv7G6gufLGG1jr2ojdJviGWmZmH9P7RN3Yl2d2u19+eveTQAD4wdzAfIot3P4bx2X4ZsievIcJqWMCalDDhNObHZsrGmhBh/5B/Tsqz4SQia+0PxFKwAPumJVoU3Jum3Gz3yMIntLSZygXFX6qTEnbS3n/N59DcAy9XRapvOxwy3IYBPxCGziDM7g4t971smCLznOsZuVFXp2Ge7aYQ3cGulzIgBT8QipEE+PGAYIyZTsVzVhLBIJKTWenyT0djnmdj3GUdcbokiRnYoBhPx+nrjq/THeJFDFC6nwRpzhtsvJQ4UssPnoKkhm36lAG+MYocCFtjqcdP+hKnmJX3VNmJoYnfJ059LrVbM1L/6qfKOS3Ccyi9RGCP6oeUSPbGIb5OKEuo3rr43LrF9bM3LibxTrX3ScCM9grOcBBBpt1hfVn+aDPXe+unQofnSg7y4AS2wc3Gl6dT0SaBZS/vJtDYT2rdiQ3yCKFrGDOYtLAQvMRiw1tyAvrok9zG6tDld07/0rJXE7rUoi/71MCNc9JizO2u16I9rlcHCWIhk3GKDBY1RM0eFqi3QrmPrroP4iZlUwcKXQWWFlnHEbbs9ARP4987MQ3zLA44phQ=
#      - secure: rDzarH4FeF7atzG2uT+Tjr7Xd4mIHgYa2B/UPV19qbqIa9Q6Z6UV8hvgGY/HrWWk/TxJRKVUxkudbMFFpYB4oNICyazGVBSDzevo+eTzlQMdca77W176/bhN8tRhkawawrS/ZXqCOj1RXmprw/Ngydqk8D/bk8qKlWIoivNdLsdubnBaC4G230WItQfu/hAtUWlPM23pPnpHhdtZYvy/BV0/H9y439tjGRKq9rQY1eKR4eV4s2ZcnR5nIsqSiXzspWoRM8BMTkqoKxUSUKkptcfwbB/AR7yJ0ocxTP0TVC2nmgAV2r7JjRtu5Xtf6bNbPTDnqWTICNOhm/lomnEexRyPIl3I0QA8q6M5sLvJ3Y4YftDWkFfiQdG3B51mp5puhbQYXaT19LqTWkYflPO3mF3H88U/ffotNIpmuNKXc2myIlzmaWcBfXcoDLxrF1LD+KS7+aTLfgSiG74J6xC+KukZbA0eG3gEflQkKvmed+H/pk3I6M9mdqsCUt8GDYi5UatsVCwzeQbFmlU6VjZo5v3sgi6xdJAMgN2C4+la25Ecyj6Z3P9Y7BsJ1jBA+9Fjbo6hDXOzim+G/+Cr6rT6aY77e1bB52EHsngHqYdsb2wK08tPNXZLpkW4dtlhKgS1iJHUWVZU6E+jIYE9WLMSHqOCo4UX4j58M8IL0a9VmPI=
     # PASSPHRASE
     - secure: H3rmTvpwyF3KcVBEqKqIWVatQDgfKykuIJ9TRu2N4HuNCPhhYlzY60fPR0F4XUcakojZB9Txp0PpEXmUwh3OZNs8a+DIghFA6abE+poagjMH3XW3rlS9x8/OMrzwqAiFWBB4Tqr7xZNtv7GFRf8hzxniieMQyBYSuQOefFNzY6dVH/VztbR/nQln4tVrkbhElgJ6xTKpDv0NQLyJ+6rIaqrOWVLsCpgAwY8OT6fIqV0+tpCLb+h25mfpd337kANb1pX2bw6zcqVgtXQAErEvZPgAIFZeoIFVZfR5scG8HlP1UxjSFPfGUE0rjtzSQ2/i/LSjp1qG6rviZkLFQEUUfhhQjPBqX1HWSRu+WM5ZvxgaNqgrgTz7QT7veuEqbtep636fP5Ld3BCX9+4xc/nlSIyqCzrnxUePgJAMuLczLumTVcrOaa3DSzQ7k6/mPSGKCUrkEODQdqAjTOPnapveindWX3hmtg4GuwM0ft+Em++DI2zJPzz14lVvxGikW/KPucn5kyZ9ePhXvnpLgnMcF+/lchPis+JoBnQm8AzjW4MCOP6r/zsC7obaCKympF/o06TZPkATnlSHtOS9kojBCuZmEx0pIB3ZBPPUH8kcNhPsAoxBWqRcttvUg4/Ccx3j9V0tIhyUE/mgj/12SMhX1U3KuIP1ke2ScTFzKwNT620=

language: java

jdk:
- oraclejdk8

notifications:
  email: false

cache:
  directories:
  - "$HOME/.m2"

before_install:
- sed -i -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  ~/.m2/settings.xml
- unzip ./src/main/resources/repogit4testv0.zip

# in Java/Maven mvn takes care of the dependencies
install: true

# this is where all tests are executed
script: mvn test

after_success:
- ".buildscript/deploy_to_maven.sh"

dist: trusty
